environemnt set up
Running the batch script
2020-12-19 11:25:38.801394: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-19 11:25:52.555688: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-19 11:25:52.585511: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2900000000 Hz
2020-12-19 11:25:52.589798: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55946e98bb10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-19 11:25:52.589844: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-12-19 11:25:52.596811: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-12-19 11:25:52.905978: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55946e98e310 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-12-19 11:25:52.906048: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100S-PCIE-32GB, Compute Capability 7.0
2020-12-19 11:25:52.914881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2020-12-19 11:25:52.914950: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-19 11:25:52.921383: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-19 11:25:52.926883: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-19 11:25:52.929121: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-19 11:25:52.934587: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-19 11:25:52.938608: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-19 11:25:52.948747: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-19 11:25:52.955250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-19 11:25:52.956294: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-19 11:25:55.652246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-19 11:25:55.652312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-12-19 11:25:55.652330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-12-19 11:25:55.682891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:0 with 30132 MB memory) -> physical GPU (device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2020-12-19 11:25:55.690265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2020-12-19 11:25:55.690319: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-19 11:25:55.690351: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-19 11:25:55.690378: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-19 11:25:55.690399: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-19 11:25:55.690418: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-19 11:25:55.690439: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-19 11:25:55.690459: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-19 11:25:55.696367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-19 11:25:55.696407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-19 11:25:55.696420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-12-19 11:25:55.696431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-12-19 11:25:55.701799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:0 with 30132 MB memory) -> physical GPU (device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2020-12-19 11:25:56.143591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2020-12-19 11:25:56.143644: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-19 11:25:56.143668: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-19 11:25:56.143680: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-19 11:25:56.143691: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-19 11:25:56.143703: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-19 11:25:56.143714: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-19 11:25:56.143725: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-19 11:25:56.146853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-19 11:25:56.148808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Tesla V100S-PCIE-32GB computeCapability: 7.0
coreClock: 1.597GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 1.03TiB/s
2020-12-19 11:25:56.148837: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-12-19 11:25:56.148855: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-19 11:25:56.148866: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-12-19 11:25:56.148876: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-12-19 11:25:56.148887: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-12-19 11:25:56.148897: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-12-19 11:25:56.148908: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-12-19 11:25:56.151981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-12-19 11:25:56.152014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-19 11:25:56.152022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-12-19 11:25:56.152029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-12-19 11:25:56.155257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30132 MB memory) -> physical GPU (device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
Using TensorFlow backend.
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x2b0ab5ad4e18> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Does the system is built with CUDA?: True
Default GPU Device: /device:GPU:0
====> Start running baseline.py
Classes: ['Tomato___Late_blight', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Peach___healthy', 'Grape___Esca_(Black_Measles)', 'Potato___Late_blight', 'Pepper,_bell___Bacterial_spot', 'Strawberry___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Tomato___Leaf_Mold', 'Apple___Black_rot', 'Strawberry___Leaf_scorch', 'Tomato___Early_blight', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Common_rust_', 'Blueberry___healthy', 'Potato___Early_blight', 'Pepper,_bell___healthy', 'Apple___Cedar_apple_rust', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Tomato___Tomato_mosaic_virus', 'Tomato___Target_Spot', 'Tomato___healthy', 'Peach___Bacterial_spot', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Corn_(maize)___healthy', 'Squash___Powdery_mildew', 'Cherry_(including_sour)___Powdery_mildew', 'Tomato___Bacterial_spot', 'Grape___Black_rot', 'Apple___healthy', 'Potato___healthy', 'Corn_(maize)___Northern_Leaf_Blight', 'Tomato___Septoria_leaf_spot', 'Raspberry___healthy', 'Soybean___healthy', 'Apple___Apple_scab', 'Grape___healthy']
Number of classes: 38
Total number of images: 54305
first_folder_path: /fs/scratch/PAA0023/dong760/PlantVillage-Dataset/raw/color/Tomato___Late_blight
Number of folder: 38
sample image path: /fs/scratch/PAA0023/dong760/PlantVillage-Dataset/raw/color/Tomato___Late_blight/5fdf3288-d5f4-4c70-9b12-95222b82d415___RS_Late.B 4942.JPG
Image size: (256, 256, 3)
Found 43456 images belonging to 38 classes.
Found 10849 images belonging to 38 classes.
Train size: 43456

====> Statistics: epochs=3, batch_size=32, validation_split=0.2, lr=0.001, momentum=0.9, steps_per_epoch =100, feature shape= (256, 256, 3), no_classes=38, loss_function=categorical_crossentropy
Epoch 1/3
2020-12-19 11:26:10.109794: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-12-19 11:26:10.738132: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x2b0ab6b18400> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
100/100 - 126s - loss: 1.8460 - tp: 1057.0000 - fp: 97.0000 - tn: 118303.0000 - fn: 2143.0000 - accuracy: 0.5325 - precision: 0.9159 - recall: 0.3303 - auc: 0.9217 - val_loss: 0.9158 - val_tp: 1908.0000 - val_fp: 129.0000 - val_tn: 118271.0000 - val_fn: 1292.0000 - val_accuracy: 0.7700 - val_precision: 0.9367 - val_recall: 0.5962 - val_auc: 0.9836
Epoch 2/3
100/100 - 125s - loss: 0.8039 - tp: 2132.0000 - fp: 169.0000 - tn: 118231.0000 - fn: 1068.0000 - accuracy: 0.7912 - precision: 0.9266 - recall: 0.6662 - auc: 0.9844 - val_loss: 0.5813 - val_tp: 2350.0000 - val_fp: 157.0000 - val_tn: 118243.0000 - val_fn: 850.0000 - val_accuracy: 0.8503 - val_precision: 0.9374 - val_recall: 0.7344 - val_auc: 0.9935
Epoch 3/3
100/100 - 123s - loss: 0.5183 - tp: 2462.0000 - fp: 168.0000 - tn: 118232.0000 - fn: 738.0000 - accuracy: 0.8553 - precision: 0.9361 - recall: 0.7694 - auc: 0.9952 - val_loss: 0.5480 - val_tp: 2497.0000 - val_fp: 231.0000 - val_tn: 118169.0000 - val_fn: 703.0000 - val_accuracy: 0.8466 - val_precision: 0.9153 - val_recall: 0.7803 - val_auc: 0.9916
WARNING:tensorflow:From /users/PAA0023/dong760/miniconda3/envs/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-12-19 11:32:34.436541: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /users/PAA0023/dong760/miniconda3/envs/tf_latest/lib/python3.6/site-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x2b0b358e2bf8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
{'loss': [1.8459694385528564, 0.8038998246192932, 0.5182905793190002], 'tp': [1057.0, 2132.0, 2462.0], 'fp': [97.0, 169.0, 168.0], 'tn': [118303.0, 118231.0, 118232.0], 'fn': [2143.0, 1068.0, 738.0], 'accuracy': [0.5325000286102295, 0.7912499904632568, 0.8553125262260437], 'precision': [0.915944516658783, 0.9265536665916443, 0.9361217021942139], 'recall': [0.33031249046325684, 0.6662499904632568, 0.7693750262260437], 'auc': [0.9217336773872375, 0.9843792915344238, 0.9951601028442383], 'val_loss': [0.9158360362052917, 0.5813299417495728, 0.5479817390441895], 'val_tp': [1908.0, 2350.0, 2497.0], 'val_fp': [129.0, 157.0, 231.0], 'val_tn': [118271.0, 118243.0, 118169.0], 'val_fn': [1292.0, 850.0, 703.0], 'val_accuracy': [0.7699999809265137, 0.8503124713897705, 0.8465625047683716], 'val_precision': [0.9366715550422668, 0.9373753666877747, 0.9153226017951965], 'val_recall': [0.5962499976158142, 0.734375, 0.7803124785423279], 'val_auc': [0.9836070537567139, 0.9935299754142761, 0.9916175007820129]}
date and time = 19-12-2020_11-32-27
Traceback (most recent call last):
  File "plant_leaves_diagnosis/baseline.py", line 307, in <module>
    dot_img_file = BASE_DIR+"/model_graphs/"+MODEL_NAME+"_batchsize_"+str(batch_size)+"_"+str(dt_string)
  File "/users/PAA0023/dong760/miniconda3/envs/tf_latest/lib/python3.6/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 306, in plot_model
    dpi=dpi)
  File "/users/PAA0023/dong760/miniconda3/envs/tf_latest/lib/python3.6/site-packages/tensorflow/python/keras/utils/vis_utils.py", line 114, in model_to_dot
    raise ImportError(message)
ImportError: ('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


p0312.ten.osc.edu:
                                                                               Req'd  Req'd   Elap 
Job id               Username Queue    Name                 SessID NDS   TSK   Memory Time Use S Time 
-------------------- -------- -------- -------------------- ------ ----- ----- ------ ----- - -----
2564371              dong760  gpuseria ondemand/sys/dashboa --         1    28     -- 05:00 R 01:42
2564451              dong760  gpuseria plant_disease_diagno --         1    48     -- 04:00 R 00:07
2564453              dong760  gpuseria plant_disease_diagno --         1    48     -- 04:00 R 00:03
2564455              dong760  gpuseria plant_disease_diagno --         1    48     -- 04:00 C 00:00
The date when running current script is :
Sat Dec 19 11:32:50 EST 2020
